management.endpoints.web.exposure.include=health

spring.datasource.url =jdbc:mysql://terraform.c3uymco0yeyo.us-east-2.rds.amazonaws.com/terraform
spring.datasource.username = aiops
spring.datasource.password = capgemini

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# HikariCP connection pool settings
spring.datasource.hikari.maximum-pool-size=500
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=100000
spring.datasource.hikari.connection-timeout=20000
#spring.datasource.hikari.leak-detection-threshold=15000

# 60 seconds in milliseconds

spring.jpa.open-in-view=false

management.metrics.export.cloudwatch.namespace=AIOPS
management.metrics.export.cloudwatch.step=1m
management.metrics.export.cloudwatch.enabled=true
cloud.aws.region.auto=false
cloud.aws.region.static=us-east-2
cloud.aws.stack.auto=true
cloud.aws.credentials.use-default-aws-credentials-chain=true

logging.level.com.amazonaws=DEBUG
logging.level.io.micrometer=DEBUG
logging.level.org.springframework.boot=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.cloud=DEBUG
logging.level.software.awssdk=DEBUG


