name: Deploy to AWS EC2

on:
  push:
    branches: [ deploy-to-EC2 ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'

      - name: Deploy to EC2
        run: |
          # Copy your JAR file to the EC2 instance
          scp -i C:\Users\sayadutt\AIOPS-Ohio-KeyPair.pem C:\Users\sayadutt\Repository\springboot-aws-ecs\target\springboot-example,jar ec2-user@ec2-3-22-60-46.us-east-2.compute.amazonaws.com:/opt/my-application/

          # Restart the application service on the EC2 instance
          ssh -i C:\Users\sayadutt\AIOPS-Ohio-KeyPair.pem ec2-user@ec2-3-22-60-46.us-east-2.compute.amazonaws.com 'sudo systemctl restart your-application'
