name: Deploy to AWS EC2

on:
  push:
    branches: [ deploy-to-EC2 ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'

      - name: Deploy to EC2 machine
        run: |
          chmod 400 /home/runner/work/springboot-aws-ecs/springboot-aws-ecs/AIOPS-Ohio-KeyPair.pem
          mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
          ssh-keyscan -H ec2-3-22-60-46.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
          scp -i ${{ github.workspace }}/AIOPS-Ohio-KeyPair.pem ${{ github.workspace }}/target/springboot-example.jar ec2-user@ec2-3-22-60-46.us-east-2.compute.amazonaws.com:/opt/my-application
          ssh -i ${{ github.workspace }}/AIOPS-Ohio-KeyPair.pem ec2-user@ec2-3-22-60-46.us-east-2.compute.amazonaws.com 'pkill -f springboot-example.jar && nohup java -jar /opt/my-application/springboot-example.jar &'
